#!/bin/bash
#---------------------
# Testing /usr/bin/glance-* shebangs
#---------------------
set -e

BINARIES=('glance-api' 'glance-cache-cleaner' 'glance-cache-manage' \
          'glance-cache-prefetcher' 'glance-cache-pruner' \
          'glance-control' 'glance-manage' 'glance-registry' \
          'glance-replicator' 'glance-scrubber' 'glance-wsgi-api')

ret=0

for binary in "${BINARIES[@]}"; do
    if ! `dirname $0`/test-shebang.py $binary python3.6; then
        ret=1
    fi
done

exit $ret
